### ISSUE TITLE
Support for AC0850 removed!?

### ISSUE THREAD

**Issue by szamfirov** [kongo09/philips-airpurifier-coap#167] opened 2024-10-26 09:28 UTC
Hi there,

First of all I want to say thanks for the great HACS add-on. I've been using it for quite a while without any issues.

I've just upgraded to the latest version (v0.18.11) and I noticed that one of my air purifiers (800 series / AC0850) is being no longer available. I had to dig deeper to find out that it's no longer supported!? Is this temporary or a potential bug?

The integration was working w/o any issues for this model before that release.

Here are the errors that I'm seeing in case useful:
```
2024-10-26 09:09:10.032 ERROR (MainThread) [custom_components.philips_airpurifier_coap.fan] Unsupported model: AC0850
2024-10-26 09:09:10.032 ERROR (MainThread) [custom_components.philips_airpurifier_coap.light] Unsupported model: AC0850
2024-10-26 09:09:10.033 ERROR (MainThread) [custom_components.philips_airpurifier_coap.number] Unsupported model: AC0850
2024-10-26 09:09:10.033 ERROR (MainThread) [custom_components.philips_airpurifier_coap.select] Unsupported model: AC0850
2024-10-26 09:09:10.041 ERROR (MainThread) [custom_components.philips_airpurifier_coap.switch] Unsupported model: AC0850
```

**Comment by szamfirov** [comment] 2024-10-26 10:40
I've reverted back to v0.18.9 again just to get things working but I'm still interested in the resolution of this issue.

/cc @kongo09

**Comment by kongo09** [comment] 2024-10-26 11:26
It is still supported, but you need to remove it and manually add it back. All entities should reappear as they were before. I'm sorry that I didn't write a migration logic. The problem is, that there are more than one AC0850 model out there that use an entirely different logic to control, even though they're otherwise the same and report the same model number. The integration now looks for the firmware version to detect the difference.

I'll close this now but feel free to reopen if you can't get it resolved.

**Closed as completed by kongo09** 2024-10-26 11:26 UTC
