### ISSUE TITLE
AC0850/85 Power On/Off Issue

### ISSUE THREAD

**Issue by Gorilla0823** [kongo09/philips-airpurifier-coap#203] opened 2024-11-22 20:29 UTC
**Description:**
I am experiencing an issue with the AC0850/85 where the power on/off functionality is not working as expected. When I try to power on/off the device, it does not respond correctly.

**Steps to Reproduce:**
Just click the power on/off switch symbols on the panel.

**Expected Behavior:**
The AC0850/85 should power on/off when the respective command is issued.

**Actual Behavior:**
The device does not respond to the power on/off commands.

**Version:**
Firmware Version: 0.24.0

**Additional Information:**
![image](https://github.com/user-attachments/assets/968cb072-abf8-4ca5-a1e6-8e7a8aeb7c60)

**Request:**
Please investigate and fix this issue.

**Comment by kongo09** [comment] 2024-11-22 20:49
Can you please share the debug log files

**Comment by Gorilla0823** [comment] 2024-11-22 21:05
## Debug Log  
[home-assistant_philips_airpurifier_coap_2024-11-22T20-55-53.243Z.log](https://github.com/user-attachments/files/17876360/home-assistant_philips_airpurifier_coap_2024-11-22T20-55-53.243Z.log)

I’ve attached the relevant portion of the debug log to help diagnose the issue. Let me know if you need more details!  

## Attachment  
- `[home-assistant_philips_airpurifier_coap_2024-11-22T20-55-53.243Z].log`

**Comment by kongo09** [comment] 2024-11-22 21:12
I don't see any error from the integration in the log file.

**Comment by kongo09** [comment] 2024-11-22 21:34
This might actually be a duplicate of #179

**Comment by Gorilla0823** [comment] 2024-11-22 21:39
## Debug Log  

[home-assistant_philips_airpurifier_coap_2024-11-22T21-33-57.772Z.log](https://github.com/user-attachments/files/17876615/home-assistant_philips_airpurifier_coap_2024-11-22T21-33-57.772Z.log)

Sorry, I didn’t configure the debug log properly before. I’ve attached a new one for your reference. Thank you for your help!

## Attachment  
- `home-assistant_philips_airpurifier_coap_2024-11-22T21-33-57.772Z.log`

**Comment by kongo09** [comment] 2024-11-22 21:55
The log only shows that HA is struggling to get a connection with your device, but not much more. Can you try the latest beta where just changed something for the startup?

If that doesn't work, please remove and add your device again while the debug log is enabled.

**Comment by Gorilla0823** [comment] 2024-11-23 14:15
![image](https://github.com/user-attachments/assets/94a7a061-f411-4bdd-92f0-aa19be5afc51)
I tried using the latest beta, but it shows ‘model unsupported’. I have attached a screenshot to explain it.

**Comment by kongo09** [comment] 2024-11-23 15:18
I need debug logs, please.

**Comment by Gorilla0823** [comment] 2024-11-23 17:51
I would like to ask how to generate a debug log in this situation. Should I downgrade the version for testing, or is there another way to obtain this information? Thank you.

**Comment by kongo09** [comment] 2024-11-23 18:07
Go to settings, system, logs and check the standard HA log

**Comment by Gorilla0823** [comment] 2024-11-23 19:03
I encountered the following warning when adding a new device as you instructed. Please take a look at the issue, as shown in the image. Thank you.
![image](https://github.com/user-attachments/assets/8a237f35-ad14-457a-9d5e-13db3ad610ec)

**Comment by kongo09** [comment] 2024-11-23 20:30
This is only of some help. The real log would be better.

**Comment by Gorilla0823** [comment] 2024-11-23 21:53
Okay.I roughly understand your meaning. May I ask if this is okay? I have output the relevant log.
[home-assistant_2024-11-23T21-50-03.840Z.log](https://github.com/user-attachments/files/17882671/home-assistant_2024-11-23T21-50-03.840Z.log)

**Comment by kongo09** [comment] 2024-11-24 10:00
I have an idea - there are two different versions of the AC0850 and I don't know which version the AC0850/85 is. 

If you use the Air+ app, can you please open the page for your device. There is a cog-wheel for settings in the top right. You then find a menu entry called "Device Information" or something like this. On my AC0850 it is the third entry from the top. Inside, you find some information on the WLAN-Firmware. Can you please send me the WLAN-Firmware name?

**Comment by kongo09** [comment] 2024-11-24 14:26
Please try v0.27.0-beta.1

**Closed as completed** 2024-11-24 15:20 UTC
Labels: bug, duplicate

**Comment by Gorilla0823** [comment] 2024-11-24 15:26
Thank you very much for your correction. He can successfully operate the switch now.

**Comment by kongo09** [comment] 2024-11-24 15:33
That's great. If you like to support my work, [you can get me a coffee](https://buymeacoffee.com/kongo09)
