### ISSUE TITLE
Adding AC0650/10

### ISSUE THREAD

**Issue by K3vb3rt** [kongo09/philips-airpurifier-coap#101] opened 2023-12-27 19:06 UTC
Hi guys,
I'm trying to add the AC0650 via the integration. As I can see it is not officially supported, so I was trying to gather the raw status-data through the virtual environment. 
In terminal from HomeAssistant I was already able to create the environment, but when I execute command aioairctrl --host $DEVICE_IP status --json with my IP **aioairctrl --host $192.168.1.250 status --json** I get this log. 

Where is my failure/mistake? What can I do to integrate my purifier? :)

Thank you & regards

<img width="741" alt="Bildschirmfoto 2023-12-27 um 20 05 18" src="https://github.com/kongo09/philips-airpurifier-coap/assets/60546306/1aa855a5-fb5e-4538-9759-65ba6dd81a2b">

**Comment by Anashost** [comment] 2023-12-29 22:16
I had the same issue in the past, i think the tool `aioairctrl` is not installed correctly. Try `apt update` & `apt upgrade` before you install it. If still not working try python3 instead.

**Comment by kongo09** [comment] 2024-01-06 02:02
Did you get `aioairctrl` working in the end? I can only support the model if you provide data.

**Comment by kongo09** [comment] 2024-01-06 02:12
From the handbook, the AC0650/10 looks pretty similar to the AC0850. If you're willing to test, I can do a release using the codes of the AC0850 and you can try and report back if it works.

**Comment by PoshAlchemist** [comment] 2024-01-06 20:25
Hi, I also have the ac0650 but it's /20 not 10, do t know what the difference is, tried a quick Google but could see anything. 
I'm happy to test if the ac850 codes works, if not happy to grab the codes from the ac0650 but unable to do this until Monday as away from pc to do the python part but do have remote access to ha so can at least test the ac850 side

**Comment by PoshAlchemist** [comment] 2024-01-08 11:19
So i tried to get the output of aioairctrl and hit a stumblng block ... 
when i try and run 
aioairctrl --host $DEVICE_IP status --json
i get the same error as in the OP - socket.gaierror: [Errno 11001] getaddrinfo failed

I tried the same command without the $ and it doesnt error but its just sitting threre.  If change the state of the ac0650 i get nothing output .... 

If i run the above in debug (--debug) i get the following :

DEBUG:aioairctrl.coap.client:syncing
DEBUG:coap:Sending request - Token: 69b9, Remote: <_Connection at 0x14e21d567d0 on transport <_ProactorDatagramTransport fd=664 read=<_OverlappedFuture pending cb=[_ProactorDatagramTransport._loop_reading()]>>, active>
DEBUG:coap:Sending message <aiocoap.Message at 0x14e225e0890: NON POST (MID 60309, token 69b9) remote <_Connection at 0x14e21d567d0 on transport <_ProactorDatagramTransport fd=664 read=<_OverlappedFuture pending cb=[_ProactorDatagramTransport._loop_reading()]>>, active>, 1 option(s), 8 byte(s) payload>

again after the above message it just hangs there, even after triggering the ac0650
However if i enter a random ip address i get the same. so that doesnt seem right

Guess my first question is should i put the $ in ip address or not 
ie 192.168.1.2 vs $192.168.1.2 
 and also when i change commands should i see the output in the console or does it just write it to the json (if so where is that json  i cant find it) i tried not specifiying --json but still nothing output to screen - its also not appearing in HA logs either (i added the config entry) 
 
 I guess first step is to ensure i have successfully made that connection, is there a way to test that?  ... could the default port of COAP have changed maybe?

Thanks for any help ... 
PS im running python from windows if that makes any difference

**Comment by Anashost** [comment] 2024-01-08 11:42
I think that's your issue, better use a Linux vm, in my case ubuntu did the trick, just make sure to update all packages before trying the steps.

**Comment by PoshAlchemist** [comment] 2024-01-08 11:58
Thanks will do, 
2 things : 

- do i add the $ to the ip address (im a windows bod and $ normally indicates a var so just want to check
- should i see anything output to screen when successfully connected \ triggering a command via the app 

If i know that at least i can keep trying things until i get it to work , just not sure what the feedback of success looks like

**Comment by Anashost** [comment] 2024-01-08 12:03
> * do i add the $ to the ip address (im a windows bod and $ normally indicates a var so just want to check

I would try with and without it

> * should i see anything output to screen when successfully connected \ triggering a command via the app

Yes you will see a json response in the terminal, after each command from the app.

**Comment by PoshAlchemist** [comment] 2024-01-08 12:05
excellent thanks, firing up my linux desktop now so will see how i get on. 
thanks for the help

**Comment by Anashost** [comment] 2024-01-08 12:17
No worries

**Comment by PoshAlchemist** [comment] 2024-01-08 12:38
Ok from ubuntu ... everything has been updated .... 

- Using $ infront of IP
   It connects but same issue as before sending commands does not trigger any respone 

- NOT using $ in the IP 
  I get an error but this time its a different error : 
    " aiocoap.error.NetworkError: [Errno 111] received through errqueue "
Googling this and its saying that it is due to Connection Refused ... which could be the issue (not sure why though)

Before i go down the rabbit hole of investigating that (which could just be because its a wrong ip as its expecting the $) it would be good to confirm if the $ is needed or not.

Do you think you could test using the $ with a device you know works then we know if its needed or not . From there i know which path \ issue to investigate

Thanks
Steve

**Comment by Anashost** [comment] 2024-01-08 12:47
I will test today with my device, and report back.

**Comment by kongo09** [comment] 2024-01-08 12:49
No $ needed, just the IP

I fear your device doesn't talk encrypted CoAP. You could try with this tool and see if a plain connection works: https://github.com/rgerganov/py-air-control

**Comment by PoshAlchemist** [comment] 2024-01-08 12:56
Ok thanks, will give that a go in abit, need to get at least a little work done today :p 
@Anashost thanks for all your help so far, looks like you don't need to check now :) thanks for offering though

**Comment by Anashost** [comment] 2024-01-08 13:01
There's still a hope, i had many issues trying to get the json responses in the past until it worked, now just waiting @kongo09 to have some spare time to add support for this #95 device :-)

**Comment by PoshAlchemist** [comment] 2024-01-08 17:40
Hey Guys, Just an update from myside. 
Using the airctrl commands from the https://github.com/rgerganov/py-air-control repo and still no luck. 

- airctrl --ipaddr <ipaddy>  = gives connection refused error

- adding --protocol coap      =  Give up on message From None, To ('<ipaddy>', 5683), CON-48080, POST-OL, [Uri-Path: sys, Uri-Path: dev, Uri-Path: sync, ] C42FE7B4...8 bytes. 
Then says : Exception: sync timeout

- changing protocol to --protocol plain_coap  = Give up on message From None, To ('<ipaddy>1', 5683), CON-8043, EMPTY-None, [] No payload

Not sure if its my network thats the issue or the device ... will do some more digging but thought i would just give an update. 

Worse case i will add the google sdk and send commands to google to control it (ive added it to google home) ... would obv rather do it via this integration if possible, shame phillips makes this such hard work

**Comment by PoshAlchemist** [comment] 2024-01-08 17:43
@K3vb3rt  Have you had any more luck? Maybe you could try the above repo too see if you have any luck. Might help to prove either way if  its the device or my network

**Comment by damda58** [comment] 2024-01-08 18:01
Good morning,

I tested the repository and I got the same results as PoshAlchemist

Coap encryption:
`(env) root@test-linux:/opt/test# airctrl --ipaddr 192.168.1.212 --protocol coap
Give up on message From None, To ('192.168.1.212', 5683), CON-24916, POST-f09f, [Uri-Path: sys, Uri-Path: dev, Uri-Path: sync, ] 132F3448...8 bytes
Traceback (most recent call last):
  File "/opt/test/env/bin/airctrl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/test/env/lib/python3.11/site-packages/pyairctrl/airctrl.py", line 205, in main
    c = CoAPCli(device["ip"], debug=args.debug)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/test/env/lib/python3.11/site-packages/pyairctrl/airctrl.py", line 99, in __init__
    super().__init__(CoAPAirClient(host, port, debug))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/test/env/lib/python3.11/site-packages/pyairctrl/coap_client.py", line 82, in __init__
    self._sync()
  File "/opt/test/env/lib/python3.11/site-packages/pyairctrl/coap_client.py", line 100, in _sync
    raise Exception("sync timeout")
Exception: sync timeout
`

Plain_Coap: 
`(env) root@test-linux:/opt/test# airctrl --ipaddr 192.168.1.212 --protocol plain_coap
Give up on message From None, To ('192.168.1.212', 5683), CON-11019, EMPTY-None, [] No payload
`

**Comment by kongo09** [comment] 2024-01-08 18:01
Could be a stupid firewall, or VLAN or Switch or whatever thing on your network?

I'll close this issue here, as I don't think it relates to the actual integration. Not much point in copying the AC0850 settings if even `aioairctrl` can't connect. Please feel free to reopen if anyone manages to extract some real data out of the AC0650.

**Closed as completed** 2024-01-08 18:01 UTC
Labels: wontfix, support model

**Comment by kyvandoan** [comment] 2024-01-13 08:49
Jumping in a closed thread. But I just acquired an AC0650 air purifier. While it looks quite similar to the AC0850, it does look like the AC0650 lacks of features. 

The Philips Air+ app can only control it, no values are being returned (guess no air sensor in it). 

I tried checking for any opened ports on that device, on a quick netcat, nothing seems open. I guess this thing is only manageable through Philips Cloud service, so web based.

**Comment by fdmadrid** [comment] 2024-11-26 16:43
Hi there, I also acquired an AC0651 air purifier.  I install the environmnet on a ubuntu pc. But no look. 
This is the response
aioairctrl --host 192.168.1.197 status --json
ConnectionRefusedError: [Errno 111] Connection refused (ECONNREFUSED, received through errqueue)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/philips-airpurifier-coap/env/bin/aioairctrl", line 8, in <module>
    sys.exit(main())
  File "/root/philips-airpurifier-coap/env/lib/python3.10/site-packages/aioairctrl/cli.py", line 139, in main
    asyncio.run(async_main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/philips-airpurifier-coap/env/lib/python3.10/site-packages/aioairctrl/cli.py", line 97, in async_main
    client = await CoAPClient.create(host=args.host, port=args.port)
  File "/root/philips-airpurifier-coap/env/lib/python3.10/site-packages/aioairctrl/coap/client.py", line 41, in create
    await obj._init()
  File "/root/philips-airpurifier-coap/env/lib/python3.10/site-packages/aioairctrl/coap/client.py", line 36, in _init
    await self._sync()
  File "/root/philips-airpurifier-coap/env/lib/python3.10/site-packages/aioairctrl/coap/client.py", line 57, in _sync
    response = await self._client_context.request(request).response
  File "/root/philips-airpurifier-coap/env/lib/python3.10/site-packages/aiocoap/protocol.py", line 758, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/root/philips-airpurifier-coap/env/lib/python3.10/site-packages/aiocoap/protocol.py", line 833, in _run
    blockresponse = await blockrequest.response
aiocoap.error.NetworkError: [Errno 111] Connection refused (ECONNREFUSED, received through errqueue)

Can somebody help me to identify what is wrong? 

Thanks for the support

**Comment by kongo09** [comment] 2024-11-26 16:55
I might be explained by the findings of @kyvandoan : there is no open port and no access locally from the outside. I did try to get in touch with Philips about the cloud based access but they never replied on any attempt. I fear we're out of luck here.

**Comment by markusstephany** [comment] 2026-04-12 07:38
There is a different approach for AC0650: https://github.com/ShorMeneses/philips-airplus-homeassistant. I created a derivative that also supports AC0651: https://github.com/markusstephany/philips-airplus-homeassistant. HTH

**Comment by kongo09** [comment] 2026-04-12 08:35
This is very interesting! It's the first time I see the cloud service reverse engineered. Have you considered creating a python library from your findings?

**Comment by markusstephany** [comment] 2026-04-12 08:48
Maybe you should contact the author of the original approach ("ShorMeneses"). I just created a derivative to get my AC0651 working. Albeit being a professional developer, I avoid whitespace-sensitive languages like Python - so I let Claude Code do all the heavy lifting :-D

**Comment by michelole** [comment] 2026-04-12 15:00
it seems there's also https://github.com/renaudallard/homeassistant_philips_homeid

**Comment by anagnorisis2peripeteia** [comment] 2026-04-26 00:47
For anyone still looking for AC0650/AC0651 control — I built a standalone Node.js package that reverse-engineers the Versuni cloud MQTT protocol (the same one the Air+ app uses):

**https://github.com/anagnorisis2peripeteia/philips-ac0650-mqtt**

It provides:
- **CLI** — `philips-ac0650 setup` walks you through OAuth login, then `status`, `on`, `off`, `speed 1-16`, `auto`, `sleep`, `turbo`, `reset clean`, `reset hepa`, `monitor`
- **Home Assistant MQTT discovery bridge** — publishes HA auto-discovery topics (fan entity + filter sensors + reset buttons) to a local MQTT broker
- **Homebridge/HomeKit plugin** — AirPurifier + FilterMaintenance services
- **HTTP REST API** — for integration with anything else

The AC0650 is cloud-only (no CoAP, no local ports as others confirmed here), so this connects via MQTT over WebSocket over TLS to AWS IoT with a custom authorizer. Uses raw MQTT 3.1.1 packets — only dependency is `ws`. Auto-refreshes OAuth tokens and MQTT signatures, auto-reconnects with exponential backoff.

Built on top of the protocol work by @ShorMeneses and @markusstephany.
